{% set name = "squirrel" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

requirements:
  host:
    - python
    - numpy
    - h5py
  run:
    - python
    - numpy
    - h5py

test:
  imports:
    - squirrel
    - squirrel.convert

about:
  home: https://github.com/jhennies/squirrel.git
  license: GPLv3
  license_family: GPL
  summary: Data conversion and handling for volume SEM (tif, h5, n5)

extra:
  recipe-maintainers:
    - jhennies
